### ISSUE TITLE
No resource found that matches the given name: attr 'indeterminate'

### ISSUE THREAD

**Issue by Coopermine** [jamesmontemagno/MonoDroidToolkit#11]
Any?

![mono](https://cloud.githubusercontent.com/assets/7460802/15938388/4532eb74-2e49-11e6-8887-bc64066d7643.png)

Build options

![buuild](https://cloud.githubusercontent.com/assets/7460802/15938445/8b6d959e-2e49-11e6-8d41-9fb5216d0724.png)

**Comment by jamesmontemagno** [comment]
Fixed this up
