### ISSUE TITLE
Unable to inflate ScaleImageView

### ISSUE THREAD

**Issue by asterixorobelix** [jamesmontemagno/MonoDroidToolkit#12]
Hi,

Thanks for the Nuget package! I have installed it in my android xamarin project.

Looking at your sample, it seems as if 
```
        <MonoDroidToolkit.ScaleImageView
            android:id="@+id/mapImage"
            android:layout_width="match_parent"
            android:layout_marginTop="5dp"
            android:layout_height="700dp"
            android:layout_marginBottom="8dp"
            android:src="@drawable/afrikaburn_map_image"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent">
        </MonoDroidToolkit.ScaleImageView>
```
I also tried the : ```MonoDroid.Toolkit.ScaleImageView``` namespace in the xml.
Is all that is required in order to get the zoom image functionality up and running. 
I've also told my fragment class which Resource.Layout to use.

But, I am getting the following exception:

```Android.Views.InflateException: Binary XML file line #1: Error inflating class MonoDroidToolkit.ScaleImageView ```

Is there something else which I should be doing?

**Comment by asterixorobelix** [comment]
By the way, the problem is that the sample in this repo uses an old namespace in the xml. Use ```com.refractored.monodroidtoolkit.ScaleImageView``` instead

**Comment by jamesmontemagno** [comment]
This will change in 2.X i am updating to new stuff now :)
