### ISSUE TITLE
Prblms installing Plugin.CurrentActivitiy v2.1.0.1

### ISSUE THREAD

**Issue by HoGo72** [jamesmontemagno/MonoDroidToolkit#15]
VS2017 15.7.1
at the Moment I've installed Plugin.CurrentActivitiy v1.0.1
When I try to update to v2.0.1.4 or v2.1.0.1 I get error

Failed to add reference. The package 'Plugin.CurrentActivity' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/CurrentActivityPlugin/issues/20
