### ISSUE TITLE
Is there any way to set cookie store to image loader?

### ISSUE THREAD

**Issue by veonua** [jamesmontemagno/MonoDroidToolkit#8]

**Comment by jamesmontemagno** [comment]
I would recommend checking out: https://components.xamarin.com/view/urlimageviewhelper for image downloading. i wrote this a long time ago.

**Comment by veonua** [comment]
This library has been deprecated, use ion instead:

any idea when ion will be available?

**Comment by jamesmontemagno** [comment]
Koushes library is great and much more up to date then mine on image
downloading and caching. I will chat with component team about ion, but ion
does a lot more.

**Comment by veonua** [comment]
there is no access to http headers in UrlImageViewHelper Library, ion has
it.

but yes ion does much more than loading images
